[versions]
minecraft      = "1.19"
quilt_loader   = "0.17.1-beta.4"
quilt_mappings = "1.19+build.1"
quilt_qsl      = "2.0.0-beta.7+1.19"

[libraries]
minecraft      = { module = "com.mojang:minecraft",       version.ref = "minecraft"      }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader   = { module = "org.quiltmc:quilt-loader",   version.ref = "quilt_loader"   }
quilt_qsl      = { module = "org.quiltmc:qsl",            version.ref = "quilt_qsl"      }