name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Enforce License Headers
        run: ./gradlew checkLicenses
      - name: Build Mod
        run: ./gradlew build
        # todo(@JustPyrrha, 23/06/2022): Run tests & gametest here
      - name: Publish Maven Snapshot
        if: success()
        env:
          ORG_GRADLE_PROJECT_mavenUsername: ci
          ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.maven_pass }}
        run: ./gradlew publish
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/libs/QTech-*.jar
            !build/libs/QTech-*-sources.jar