name: pull request
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Enforce License Headers
        run: ./gradlew checkLicenses
      - name: Build Mod
        run: ./gradlew build
        # todo(@JustPyrrha, 23/06/2022): Run tests & gametest here